spring.application.name=ControlX

#  API Key
gemini.api.key=${GEMINI_API_KEY}
# Database
spring.datasource.url=jdbc:h2:file:./data/controlx_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# (The Dialect line was removed to fix the warning)

# H2 Console - Turned on for your convenience
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger
springdoc.packages-to-scan=controller